--CREATE VIEW [dbo].[CalonSiswaFull]
--	AS SELECT ap.Id,
--		ap.JalurPendaftaran,
--		ap.NoPendaftaran,
--		ap.Status,
--		ap.
--	FROM AkunPendaftaran ap FULL JOIN CalonSiswa cs ON ap.CalonSiswaId = cs.Id
