CREATE TABLE [dbo].[Pengaturan]
(
	Id INT IDENTITY(1,1),
	Periode INT,
	SoalMipaKhusus INT,
	SoalIpsKhusus INT,
	SoalTpaKhusus INT,
	SoalWawancaraCalonSiswaKhusus INT,
	SoalWawancaraOrangTuaKhusus INT,
	SoalMipaReguler INT,
	SoalIpsReguler INT,
	SoalTpaReguler INT,
	SoalWawancaraCalonSiswaReguler INT,
	SoalWawancaraOrangTuaReguler INT,
	SoalMipaMutasi INT,
	SoalIpsMutasi INT,
	SoalTpaMutasi INT,
	SoalWawancaraCalonSiswaMutasi INT,
	SoalWawancaraOrangTuaMutasi INT,
	SoalWawancaraCalonSiswaPrestasi INT,
	SoalWawancaraOrangTuaPrestasi INT,
	SoalWawancaraCalonSiswaMitra INT,
	SoalWawancaraOrangTuaMitra INT,
	CONSTRAINT [PK_Pengaturan] PRIMARY KEY (Id)
)
