CREATE TABLE [dbo].[Soal]
(
	Id INT,
	Judul VARCHAR(50) NOT NULL,
	Kategori VARCHAR(10) NOT NULL,
	Target VARCHAR(20) NOT NULL,
	JumlahPertanyaan TINYINT,
	BatasWaktu TINYINT,
	Status VARCHAR(10) NOT NULL DEFAULT 'ENABLE',
	CONSTRAINT [PK_Soal] PRIMARY KEY(Id)
)
